# Generated by Django 3.1.4 on 2021-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboarddetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=300)),
                ('points', models.CharField(default=0, max_length=3)),
            ],
        ),
    ]
